---
# This Playbook deploys the entire k8s cluster

- hosts: all
  become: false
  roles:
  - role: common

- hosts: controllers
  become: false
  roles:
  - role: controller

- hosts: nodes
  become: false
  roles:
  - role: node