---
# Handlers for docker and kubelet

- name: docker status old
  service:
    name: docker
    state: started

- name: docker status
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted

- name: restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted