---
# Step 3.2: Join the nodes to the Kubernetes cluster using below code. 

- name: Copy the join command to server location
  copy: 
    src: temp/join-command 
    dest: /tmp/join-command.sh 
    mode: 0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
